/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function isSupported(): boolean
export declare function actuate(actuationId: number, intensity: number): void
export declare function click(): void
export declare function weakClick(): void
export declare function strongClick(): void
